CREATE TABLE arquivo( 
      id  integer generated by default as identity     NOT NULL , 
      id_cliente integer    NOT NULL , 
      id_tp_arquivo integer    NOT NULL , 
      arquivo blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE arquivo_tipo( 
      id  integer generated by default as identity     NOT NULL , 
      descricao varchar  (30)    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE carro( 
      id  integer generated by default as identity     NOT NULL , 
      id_modelo integer   , 
      placa varchar  (20)   , 
      renavam blob sub_type 1   , 
      chassi blob sub_type 1   , 
      tipo_isencao integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE carro_marca( 
      id  integer generated by default as identity     NOT NULL , 
      descricao varchar  (30)    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE carro_modelo( 
      id  integer generated by default as identity     NOT NULL , 
      modelo varchar  (30)    NOT NULL , 
      marca integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE cliente( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1   , 
      cpf varchar  (14)   , 
      rg blob sub_type 1   , 
      rg_estado integer   , 
      rg_orgao_emissor varchar  (255)   , 
      rg_data_emissao date   , 
      email varchar  (30)   , 
      endereco blob sub_type 1   , 
      numero varchar  (30)   , 
      complemento blob sub_type 1   , 
      bairro blob sub_type 1   , 
      cep varchar  (10)   , 
      municipio integer   , 
      estado integer   , 
      id_representante integer   , 
      telefone varchar  (13)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE condutor( 
      id  integer generated by default as identity     NOT NULL , 
      descricao varchar  (20)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE condutor_autorizado( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1   , 
      cpf varchar  (14)   , 
      rg blob sub_type 1   , 
      rg_estado integer   , 
      rg_orgao_emissor varchar  (255)   , 
      rg_data_emissao date   , 
      email varchar  (30)   , 
      endereco blob sub_type 1   , 
      numero varchar  (30)   , 
      complemento blob sub_type 1   , 
      bairro blob sub_type 1   , 
      cep varchar  (10)   , 
      municipio integer   , 
      estado integer   , 
      id_cliente integer   , 
      condutor integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE contrato( 
      id  integer generated by default as identity     NOT NULL , 
      id_cliente integer   , 
      id_carro integer   , 
      data_contrato date   , 
      pagamento_tipo integer   , 
      pagamento_status integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE estado( 
      id  integer generated by default as identity     NOT NULL , 
      estado varchar  (30)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE isencao_ipva( 
      id  integer generated by default as identity     NOT NULL , 
      descricao blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE municipio( 
      id  integer generated by default as identity     NOT NULL , 
      municipio varchar  (100)   , 
      id_estado integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE pagamento_arquivos( 
      id  integer generated by default as identity     NOT NULL , 
      arquivo varchar  (200)   , 
      id_contrato integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE pagamento_status( 
      id  integer generated by default as identity     NOT NULL , 
      descricao varchar  (50)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE pagamento_tipo( 
      id  integer generated by default as identity     NOT NULL , 
      descricao varchar  (50)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE representante_legal( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1   , 
      cpf varchar  (14)   , 
      rg blob sub_type 1   , 
      rg_estado integer   , 
      rg_orgao_emissor varchar  (255)   , 
      telefone varchar  (13)   , 
 PRIMARY KEY (id)) ; 

 
  
 ALTER TABLE arquivo ADD CONSTRAINT fk_arquivo_1 FOREIGN KEY (id_cliente) references cliente(id); 
ALTER TABLE arquivo ADD CONSTRAINT fk_arquivo_2 FOREIGN KEY (id_tp_arquivo) references arquivo_tipo(id); 
ALTER TABLE carro ADD CONSTRAINT fk_carro_1 FOREIGN KEY (id_modelo) references carro_modelo(id); 
ALTER TABLE carro ADD CONSTRAINT fk_carro_2 FOREIGN KEY (tipo_isencao) references isencao_ipva(id); 
ALTER TABLE carro_modelo ADD CONSTRAINT fk_carro_modelo_1 FOREIGN KEY (marca) references carro_marca(id); 
ALTER TABLE cliente ADD CONSTRAINT fk_cliente_1 FOREIGN KEY (municipio) references municipio(id); 
ALTER TABLE cliente ADD CONSTRAINT fk_cliente_2 FOREIGN KEY (estado) references estado(id); 
ALTER TABLE cliente ADD CONSTRAINT fk_cliente_3 FOREIGN KEY (rg_estado) references estado(id); 
ALTER TABLE cliente ADD CONSTRAINT fk_cliente_4 FOREIGN KEY (id_representante) references representante_legal(id); 
ALTER TABLE condutor_autorizado ADD CONSTRAINT fk_condutor_autorizado_1 FOREIGN KEY (estado) references estado(id); 
ALTER TABLE condutor_autorizado ADD CONSTRAINT fk_condutor_autorizado_2 FOREIGN KEY (municipio) references municipio(id); 
ALTER TABLE condutor_autorizado ADD CONSTRAINT fk_condutor_autorizado_3 FOREIGN KEY (rg_estado) references estado(id); 
ALTER TABLE condutor_autorizado ADD CONSTRAINT fk_condutor_autorizado_4 FOREIGN KEY (id_cliente) references cliente(id); 
ALTER TABLE condutor_autorizado ADD CONSTRAINT fk_condutor_autorizado_5 FOREIGN KEY (condutor) references condutor(id); 
ALTER TABLE contrato ADD CONSTRAINT fk_contrato_1 FOREIGN KEY (id_cliente) references cliente(id); 
ALTER TABLE contrato ADD CONSTRAINT fk_contrato_2 FOREIGN KEY (id_carro) references carro(id); 
ALTER TABLE contrato ADD CONSTRAINT fk_contrato_3 FOREIGN KEY (pagamento_tipo) references pagamento_tipo(id); 
ALTER TABLE contrato ADD CONSTRAINT fk_contrato_4 FOREIGN KEY (pagamento_status) references pagamento_status(id); 
ALTER TABLE municipio ADD CONSTRAINT fk_municipio_1 FOREIGN KEY (id_estado) references estado(id); 
ALTER TABLE pagamento_arquivos ADD CONSTRAINT fk_pagamento_arquivos_1 FOREIGN KEY (id_contrato) references contrato(id); 
ALTER TABLE representante_legal ADD CONSTRAINT fk_representante_legal_1 FOREIGN KEY (rg_estado) references estado(id); 
